<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<title>Save and delete</title>
<link rel="stylesheet" type="text/css" href="../../css/common.css" media="screen">
</head>
<body>
<?php

// don't print notice
error_reporting(E_ALL & ~E_NOTICE);

// read data from STDIN(POST data)
$postData = '';
while ($line = fgets(STDIN)) {
    $postData .= $line;
}

if (substr($postData, -2) === "--") {
	$postData = substr($postData, 0, -2);
}

// not necessary - print STDIN data
// print_r("<br><p><H1>---Got all data!---</H1></p><br><br>");
// print_r($postData);
// print_r("<p>---Data end!---</p><br><br>");

$_POST['posted_filename'] = '';

// not necessary - print SERVER array data
// echo "SERVER ";
// var_dump($_SERVER);

// not necessary - print ENV array data
// echo "\ ENV ";
// var_dump($_ENV);



// get the CONTENT_TYPE to get the boundary
$boundary = str_replace('boundary=', '', $_ENV['CONTENT_TYPE']);
$boundarys = explode(' ', $boundary);
$boundarys[1] = '--'.$boundarys[1];


// Split the data into individual fields
$fields = explode($boundarys[1], $postData);

// Process each field
foreach ($fields as $field) {
	if (empty($field)) continue;

	// Separate the field headers and value
	list($headers, $value) = explode("\r\n\r\n", $field, 2);

	// Parse the headers to get the field name (and possibly filename)
	// and get the field value (e.g., store it in $_POST)
	if (preg_match('/name="([^"]+)"/', $headers, $matches))
	{
		$fieldName = $matches[1];		
		$_POST[$fieldName] = $value;
	}
	if (preg_match('/filename="([^"]+)"/', $headers, $matches))
	{
		$fileName = $matches[1];		
		$_POST["posted_filename"] = $fileName;
	}
}

// delete unnecessary newline
if (substr($_POST['uploading_'], -2) === "\r\n") {
	$_POST['uploading_'] = substr($_POST['uploading_'], 0, -2);
}

// difine upload directory
$uploadpath = __DIR__."/../upload/";

$filename = $_POST['posted_filename'];

if ($_POST['posted_filename'])
{
	$uploadfilepath = $uploadpath.$_POST['posted_filename'];
	$myfile = fopen($uploadfilepath, "wb");
	if ($myfile > 0)
	{
		fwrite($myfile, $_POST['uploading_']);
		fclose($myfile);
	}
	echo "<H1>File save DONE!!!</H1>";
	echo "<div class=\"nav\"><a href=\"../../index.html\">Home</a>/<a href=\"../../upload_php.html\">Upload file(PHP)</a>/<a href=\"../../bigimage.html\" class=\"active\">Big image page</a>/<a href=\"../../cgi-bin/python/hello.py\">Page generated by Python</a></div>";
	print_r("Hello ".$_POST['first_name']." ".$_POST['last_name']);
	echo "<div class=\"content\"><p>File is saved.</p></div>";
	echo "<h3>Do you want to see?<br></h3>";
	echo "<a href=\"../upload/".$_POST['posted_filename']."\" target=\"_blank\">".$_POST["posted_filename"]."</a><br>";

	echo "<h3>Do you want to delete?<br></h3>";
	echo "<form action=\"delete.php\" method=\"POST\">";
	// echo "<label for=\"file_path\">File Path:</label>";
	echo "<input type=\"hidden\" value=\"".$uploadfilepath."\" name=\"deletefile\">";
	echo "<input type=\"submit\" value=\"delete\" class=\"send\"></form>";

}
else
{
	echo "file is not uploaded (or already exist)";
}

?>

</body>
</html>
